Now can go back 3 year in usage stats
oncokb/oncokb-public pull request #1155
Opened 2024-09-18 19:40 UTC by jfkonecn

closes https://github.com/oncokb/oncokb-pipeline/issues/418

2024-09-18 19:41 UTC, jfkonecn commented on src/main/java/org/mskcc/cbio/oncokb/web/rest/CronJobController.java
> -
My changes caused a type error and this code isn't used so I chose to delete it.

2024-10-10 15:22 UTC, zhx828 requested changes
- For pages with mutliple tables and other info, let's use default page size 5 -> company page, user details page.
- should we add some tests for usage-analysis-utils?

2024-10-10 15:22 UTC, zhx828 commented on src/main/webapp/app/pages/usageAnalysisPage/usage-analysis-utils.ts
> +    .filter(([key]) => isAllUsage || !key.startsWith('/api/private/'))
I noticed `key.startsWith('/api/private/'))` used a lot. I know it looks like a simple logic, but can we wrap it up as a method?

2024-10-11 19:36 UTC, zhx828 approved these changes
Thanks！

2024-10-14 12:33 UTC, merged