Add germline core proxy config
oncokb/oncokb-public pull request #1176
Opened 2024-10-21 19:14 UTC by zhx828

2024-10-21 19:18 UTC, jfkonecn requested changes

2024-10-21 19:18 UTC, jfkonecn commented on src/main/java/org/mskcc/cbio/oncokb/service/ApiProxyService.java
> +        String germlineParam = request.getParameter("germline");
Is there a way we could make a new base endpoint altogether? I feel like an annoying bug will happen because of this.

2024-10-21 20:19 UTC, zhx828 commented
Try to add an auth requirement on top.

2024-10-22 19:22 UTC, jfkonecn approved these changes

2024-10-22 19:24 UTC, merged