Add somatic/germline gene page
oncokb/oncokb-public pull request #1181
Opened 2024-10-23 17:25 UTC by zhx828

2024-10-23 21:03 UTC, jfkonecn requested changes

2024-10-23 21:20 UTC, zhx828 commented on src/main/webapp/app/components/PageContainer.tsx
> +            : 'container-fluid'
Good question. Didn't look into, inherited from the original.

2024-10-23 21:20 UTC, zhx828 commented on src/main/webapp/app/Main.tsx
> +          <AppRouts
Yup, will fix

2024-10-23 21:20 UTC, zhx828 commented on src/main/webapp/app/components/infoTile/LoETile.tsx
> +            size={'s2'}
you meant why it's not a default?

2024-10-23 21:21 UTC, zhx828 commented on src/main/webapp/app/pages/genePage/SomaticGermlineGenePage.tsx
> +export default class SomaticGermlineGenePage extends React.Component<
We have a store in this class. And we manage some observables states here too.

2024-10-24 14:32 UTC, zhx828 commented on src/main/webapp/app/components/PageContainer.tsx
> +            : 'container-fluid'
For public website, we haven't really used the @media to manage the layout. I would stick to the classname for now.

2024-10-24 19:07 UTC, jfkonecn commented on src/main/webapp/app/components/infoTile/LoETile.tsx
> +            size={'s2'}
`size={'s2'}` vs `size="s2"`

2024-10-25 02:18 UTC, merged