Recaptcha
oncokb/oncokb-public pull request #580
Opened 2021-01-05 16:38 UTC by Leowisd

Merge Recaptcha branch into Master, implemented https://github.com/oncokb/oncokb/issues/2099

Have fixed the footer clicking issue https://github.com/oncokb/oncokb-public/pull/579

2021-01-05 21:14 UTC, zhx828 requested changes
Let's do a prettier on all files. I see some file changes which can be solved if we run the prettier.

2021-01-05 21:14 UTC, zhx828 commented on src/main/java/org/mskcc/cbio/oncokb/security/uuid/UUIDFilter.java
> +    public static final String RECAPTCHA_HEADER = "reCAPTCHA";
We don't need this anymore.

2021-01-05 21:14 UTC, zhx828 commented on pom.xml
> +        </dependency>
We don't need this anymore.

2021-01-05 21:14 UTC, zhx828 commented on pom.xml
> +        <recaptcha-spring-boot-starter.version>2.3.1</recaptcha-spring-boot-starter.version>
We don't need this anymore.

2021-01-05 21:14 UTC, zhx828 commented on src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
> +  get recaptchaVerifyed() {
Do we need this?

2021-01-05 21:14 UTC, zhx828 commented on src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
> +  get recaptchaVerifyed() {
recaptchaVerified in windowStore is a observable already.

2021-01-05 22:13 UTC, Leowisd commented
> Let's do a prettier on all files. I see some file changes which can be solved if we run the prettier.

Do you mean we run prettier on master branch?

2021-01-06 17:11 UTC, zhx828 requested changes

2021-01-06 17:11 UTC, zhx828 commented on src/main/java/org/mskcc/cbio/oncokb/config/SecurityConfiguration.java
> +    // private final RecaptchaValidator recaptchaValidator;
let's get rid of this.

2021-01-06 17:11 UTC, zhx828 commented on src/main/webapp/app/App.tsx
> +    this.stores.windowStore.recaptchaVerified = false;
Shouldn't we create these in the windowStore instead?

2021-01-06 17:11 UTC, zhx828 commented on src/main/webapp/app/App.tsx
> +                this.stores.routing.location.pathname !== '/'
Let's use PAGE_ROUTE.HOME

2021-01-06 17:11 UTC, zhx828 commented on src/main/webapp/app/indexUtils.tsx
> +};
Now if we only verify once, do we still need to save the recaptcha token?

2021-01-06 17:11 UTC, zhx828 commented on src/main/webapp/app/shared/auth/RecaptchaBoundaryRoute.tsx
> +                Verifying your behavior...
```suggestion
                Verifying your identity using Google reCAPTCHA...
```

2021-01-06 17:11 UTC, zhx828 commented on src/main/webapp/app/store/WindowStore.ts
> +      if (!this.recaptchaVerified && this.windowObj.location.pathname !== '/') {
here too, change the pathname

2021-01-06 18:04 UTC, zhx828 requested changes
Looks good. Just two minor comments.

2021-01-06 18:04 UTC, zhx828 commented on src/main/webapp/app/index.tsx
> +  AUTH_UER_TOKEN_KEY,
This is no longer needed

2021-01-06 18:04 UTC, zhx828 commented on src/main/webapp/app/store/WindowStore.ts
> +  @observable recaptchaVerified: boolean;
Can we put the observables together to keep the file structured?

2021-01-06 18:04 UTC, zhx828 commented
We need to squash the commits before merging.

2021-01-06 18:25 UTC, closed without merging

2021-01-06 18:31 UTC, Leowisd commented
Made some error on squash commits on this branch, just reopen a new PR from Leowisd/recaptcha branch https://github.com/oncokb/oncokb-public/pull/591