Create page to create company users in batch
oncokb/oncokb-public pull request #787
Opened 2022-01-07 22:25 UTC by calvinlu3

This fixes [issue #2810](https://github.com/oncokb/oncokb/issues/2810)

- Quick tool that links to `/companies/:id/create-users` that supports batch user creation
- Use SimpleConfirmModal for license status change warning

Comments (standup):
- Did not automatically create a new row when any of the three field has a value
   - If an admin completes one user's info and wants to submit, then having the automatically added row will prevent them from submitting 
   - So went with the plus icon
- If there is an error, an Alert box is shown with a list of user emails and their corresponding error messages
- Used react Tabs/Tab for the Single/Batch mode

2022-01-10 18:45 UTC, zhx828 requested changes

2022-01-10 18:45 UTC, zhx828 commented on src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
> +              onKeyDown={this.onTabKey}
Sweet!

2022-01-10 18:45 UTC, zhx828 commented on src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
> +    }
Maybe process the row separately, so it will not be limited on `3`?

2022-01-10 18:45 UTC, zhx828 commented on src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
> +                    ...fieldRequiredValidation('first name'),
Let's use SHORT_TEXT_VAL which was included in https://github.com/oncokb/oncokb-public/pull/788/files#diff-0cc27ecc1a8cb220a51e7c3eac69ba556cb73dc444fa9502816ec6c1cd1254b9R78

2022-01-10 18:45 UTC, zhx828 commented on src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
> +                <i
Could you add a tooltip for this icon?

2022-01-10 19:05 UTC, calvinlu3 commented on src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
> +  loginValidation(
I added this before the error messages were added, but I think it's fine if we leave this out as the admin will see that login is already in use error after they submit anyways.

2022-01-10 19:06 UTC, calvinlu3 commented on src/main/webapp/app/pages/companyPage/CompanyPage.tsx
>    updateCompany() {
Oh good catch, thanks!

2022-01-10 19:43 UTC, zhx828 commented on src/main/webapp/app/pages/CreateCompanyUsersPage.tsx
> +  loginValidation(
Yeah, just one less endpoint to maintain.

2022-01-11 16:35 UTC, zhx828 approved these changes
Looks good. Let's do a squash merge and release.

2022-01-11 16:49 UTC, merged