Update database readonly mode
oncokb/oncokb-public pull request #799
Opened 2022-01-19 23:55 UTC by calvinlu3

This fixes [issue 2838](https://github.com/oncokb/oncokb/issues/2838)

- Created a `ReadOnlyMode` HOC that will displays a generic unavailable page
- Repository save() calls will throw an `ApiDisabledException` with status code 503 (Service Unavailable) when trying to write

2022-01-26 16:45 UTC, calvinlu3 commented
- [ ] Why use Transactional annotation and advantages?
- [ ] Identify places where Transactional is use and the object is modified

2022-02-01 16:54 UTC, calvinlu3 commented
Reviewing the failed tests in `ExceptionTranslatorIT.java`

2022-02-01 16:59 UTC, calvinlu3 commented
Okay, seems to have to do with the ControllerAdvice I defined. Will try to move the exception handling into ExceptionTranslator.java instead.

2022-02-02 22:27 UTC, zhx828 requested changes
Overall looks good. Some minor comments.

2022-02-02 22:27 UTC, zhx828 commented on src/main/webapp/app/shared/readonly/ReadOnlyMode.tsx
> + * when application is is read only mode.
```suggestion
 * when application is in read only mode.
```

2022-02-02 22:27 UTC, zhx828 commented on src/main/webapp/app/shared/readonly/ReadOnlyMode.tsx
> +  Component: any,
I think the type should at least be a JSX.Element so you can render?

2022-02-02 22:27 UTC, zhx828 commented on src/main/webapp/app/shared/readonly/ReadOnlyMode.tsx
> +                Any changes you make won't be saved at this time. The page will
Let's emphasize using `WON'T` or `will NOT`?

2022-02-02 22:27 UTC, zhx828 commented on src/main/webapp/app/shared/readonly/ReadOnlyPage.tsx
> +const DEFAULT_TITLE = 'This page is temporarily unavailable.';
May not be necessary if it's not been shared?

2022-02-02 22:27 UTC, zhx828 commented on src/main/java/org/mskcc/cbio/oncokb/aop/repository/DatabaseReadOnlyAspect.java
> +            throw new DatabaseReadOnlyException();
Can we skip this exception in `initSentry` of `OncokbPublicApp.java`?

2022-02-02 22:27 UTC, zhx828 commented on src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/DatabaseReadOnlyException.java
> +        super(ErrorConstants.SERVICE_UNAVAILABLE, "Service is temporarily unavailable", Status.SERVICE_UNAVAILABLE);
Let's be clear here. Maybe `We are not able to update the content at this moment. Service should be back momentarily.`?

2022-02-02 22:27 UTC, zhx828 commented on src/main/java/org/mskcc/cbio/oncokb/web/rest/errors/ErrorConstants.java
> +    public static final URI SERVICE_UNAVAILABLE = URI.create(PROBLEM_BASE_URL + "/service-unavailable");
Let's just use DATABASE_READ_ONLY.

2022-02-03 01:46 UTC, calvinlu3 commented
@zhx828 Thanks for review, will get these adjusted. 👍

2022-02-03 16:26 UTC, zhx828 approved these changes
LGTM 👍🏼

2022-02-07 15:39 UTC, merged